### ISSUE TITLE
RPI Pico version

### ISSUE THREAD

**Issue by epsi1on** [iliasam/STM32F4_phase_laser_rangefinder#1]
Hi,
As you have approved that rangefinder is possible with usual devices around, I am very interested to make a copy of your rangefinder with raspberry pi pico. 
I think using an digitally controlled amplifier, it is possible to make it. from this image i can see the parts which are used in the scematics, just would like to know have you used same parts as in the schematics (from [here](https://habr.com/ru/articles/213749/))?
![laser1](https://github.com/iliasam/STM32F4_phase_laser_rangefinder/assets/7839141/9fb8333f-3bf6-46dc-8ac9-50ba176ba2df)

Thanks for sharing great project

**Comment by iliasam** [comment]
Hi,
I can see that RPI Pico has ADC with max rate of 500kHz, while I had used 1.6Mhz sample rate.
I can confirm, that schematic is right.
Notice that it was based on this (as mentioned in article): http://ronja.twibright.com/schematics/inferno_receiver.png
It fact, now I can say, that this schematics is not optimal, using special TIA is better: MAX3658 or 
OPA857.
Maybe this project will be interesting for you: https://github.com/iliasam/Laser_tape_reverse_engineering

**Comment by epsi1on** [comment]
thanks

**Comment by epsi1on** [comment]
Hi there again.
I have another question, would be thankful if you give me your thoughts.
In the articles you did note that most of laser range finders do use Avalanche Photo Diode (APD) which have some disadvantages like being expensive and need high voltage like 100V or more.

Imagine a very specific and ideal case, which there is a mirror in front of laser and on the object we are trying to measure its distance, and the mirror ideally reflects 100% of laser diode, back into the photo diode. There are some prisms that intended to do these less or more (like surveying prisms).

**_This is my main question:_**
In the above case with mirror on the object, is it possible to replace APD photodiode with a Silicon photodiode (like [BPW34](https://www.vishay.com/docs/81521/bpw34.pdf))? Why producers do not use Si photodiode instead of APD?

Thank you so much

**Comment by iliasam** [comment]
You can see from this project, that ordinary photodiode can be used in rangefinder - you just need enough received light.
See also - http://www.ti.com/tool/TIDA-00663 and https://www.mantech.co.za/Datasheets/Products/OSLRF-01_LIGHTWARE.pdf

 APD has an additional feature that can be used in phase laser rangefinder - its gain is significantly depending on voltage, so APD can be used as a signal mixer. I know that this is used in laser tape measures - for shifting received signal from high frequency to low.
